#!/usr/bin/env bash

#########################################################################################
##
## Custom Loading Screen git initialiser script for Unix
##
#########################################################################################

printMessage ( ) {
    echo
    echo "  $*"
}

tryExecute ( ) {
    echo "  --$*"
    $*
    EXIT_CODE=$?
    echo
    if [ $EXIT_CODE != 0 ] ; then
       echo "  Failed with code "$EXIT_CODE", exiting..."
       exit 1
    else
       echo "  Completed with exit code $?"
    fi
}

if [ "$1" = "build" ] ; then
  printMessage "Building the jar files of Custom Loading Screen"
else
  printMessage "Setting up Custom Loading Screen for development"
fi

if [ "$1" = "build" ]; then
    tryExecute "./gradlew setupCIWorkspace"
    printMessage "Building..."
    tryExecute "./gradlew build"
    printMessage "Build Complete!"
else
    tryExecute "./gradlew setupDecompWorkspace"
    printMessage "Generating Eclipse Workspace Files..."
    tryExecute "./gradlew eclipse"
    printMessage "Generating Idea Project Files"
    tryExecute "./gradlew idea"
    printMessage "Setup complete!"
fi
